name: RenderingLib
description: Rendering without the doll parts
version: 2.12.0
homepage: https://github.com/FarragoFiction/RenderingLib
author: jadedResearcher, paradoxLands
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  js: any
  CommonLib:
    git: https://github.com/FarragoFiction/CommonLib.git
  LoaderLib:
    git: https://github.com/FarragoFiction/LoaderLib.git

dev_dependencies:
  build_runner: ^1.6.0
  build_web_compilers: ^2.3.0
